# Generated by Django 5.0.2 on 2024-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_options_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="مقاله ویژه"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "Draft"),
                    ("p", "Published"),
                    ("i", "درحال بررسی"),
                    ("b", "برگشت داده شده"),
                ],
                max_length=1,
                verbose_name="وضعیت",
            ),
        ),
    ]
